[package]
description = "LAUREL is an event post-processing plugin for auditd(8) that transforms and enriches audit logs to improve their utility for modern security monitoring setups."

extra-sources = [
  { "number" = 3, "file" = "rust-laurel.sysusers", "comments" = ["Defines user to be added for LAUREL."] },
]

extra-files = [
  "%{_sysusersdir}/rust-laurel.conf",
]

cargo-toml-patch-comments = [
    "remove unused benchmark-only dependencies",
]

[requires]
build = ["systemd-rpm-macros"]
lib = ["audit"]

[scripts.install]
pre = [
    "# sysusers",
    "install -D -p -m 0644 %{SOURCE3} %{buildroot}%{_sysusersdir}/rust-laurel.conf",
]
